branches:
  - master
  - auto
  - try

host:
  distro: fedora/29/atomic
  specs:
    secondary-disk: 10

required: true

tests:
  - env | sort
  - echo hello world
  - findmnt
  - fdisk -l

---

inherit: true

container:
  image: registry.fedoraproject.org/fedora:29

context: Container Test
