cluster:
  hosts:
    - name: host1
      distro: fedora/25/atomic
    - name: host2
      distro: fedora/25/atomic
  container:
    image: fedora:25

tests:
  - cat /etc/hosts
  - getent ahostsv4 host1
  - getent ahostsv4 host2
  - ssh host1 cat /etc/hosts
  - ssh host1 getent ahostsv4 host1
  - ssh host1 getent ahostsv4 host2
  - ssh host2 cat /etc/hosts
  - ssh host2 getent ahostsv4 host1
  - ssh host2 getent ahostsv4 host2
