cluster:
  hosts:
    - name: atomic-25-nightly
      distro: fedora/25/atomic/nightly
    - name: cloud-25-nightly
      distro: fedora/25/cloud/nightly
    - name: cloud-26-nightly
      distro: fedora/26/cloud/nightly

tests:
  - rpm-ostree status
  - ssh cloud-25-nightly rpm-ostree status
  - ssh cloud-26-nightly rpm-ostree status
